# Generated by Django 5.1.5 on 2026-01-30 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0005_template_deprecated_at_template_deprecated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('downloaded', 'Downloaded')], default='draft', max_length=20)),
                ('placeholder_data', models.JSONField()),
                ('file_path', models.FileField(blank=True, null=True, upload_to='agreements/%Y/%m/')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_agreements', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='templates.template')),
            ],
            options={
                'db_table': 'agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTemplateUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usage', to='templates.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_template_usage',
                'ordering': ['-last_used_at'],
                'unique_together': {('user', 'template')},
            },
        ),
    ]
