# Generated by Django 5.1.5 on 2026-01-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreement_agreement_id_agreement_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='regeneration_of_agreement_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
