# Generated by Django 5.1.5 on 2026-01-30 10:46

from django.db import migrations, models


def set_admin_roles_for_staff(apps, schema_editor):
    """Set admin role for existing staff users."""
    CustomUser = apps.get_model('users', 'CustomUser')
    # Set admin role for staff users
    CustomUser.objects.filter(is_staff=True).update(role='admin')


def reverse_admin_roles(apps, schema_editor):
    """Reverse migration - set all admin roles back to viewer."""
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(role='admin').update(role='viewer')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('content_manager', 'Content Manager'), ('legal_reviewer', 'Legal Reviewer'), ('admin', 'Admin')], default='viewer', max_length=20),
        ),
        migrations.RunPython(set_admin_roles_for_staff, reverse_admin_roles),
    ]
