# Generated by Django 5.1.5 on 2026-01-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('currency', 'Currency'), ('pan_number', 'PAN Number'), ('gst_number', 'GST Number'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('position_index', models.IntegerField(default=0)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='templates.template')),
            ],
            options={
                'db_table': 'placeholders',
                'ordering': ['position_index'],
                'unique_together': {('template', 'name')},
            },
        ),
    ]
