# Generated by Django 5.1.5 on 2026-01-30 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_template_approved_at_template_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='templates.template'),
        ),
    ]
