# Generated by Django 5.1.5 on 2026-02-03 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_template_deprecated_at_template_deprecated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVisualMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_html', models.TextField(help_text='Cached HTML rendering of the template')),
                ('page_data', models.JSONField(default=dict, help_text='Page breaks, dimensions, and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_mapping', to='templates.template')),
            ],
            options={
                'db_table': 'template_visual_mappings',
            },
        ),
        migrations.CreateModel(
            name='PlaceholderVisualMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='Which page this marker appears on (1-indexed)')),
                ('x_position', models.FloatField(help_text='X coordinate (percentage from left)')),
                ('y_position', models.FloatField(help_text='Y coordinate (percentage from top)')),
                ('width', models.FloatField(help_text='Width (percentage of page width)')),
                ('height', models.FloatField(help_text='Height (percentage of page height)')),
                ('marker_color', models.CharField(default='#DC2626', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placeholder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_marker', to='templates.placeholder')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='templates.templatevisualmapping')),
            ],
            options={
                'db_table': 'placeholder_visual_markers',
                'ordering': ['page_number', 'y_position', 'x_position'],
            },
        ),
    ]
