# Generated by Django 5.1.5 on 2026-02-03 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_visual_editor_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Internal name: party_a_name', max_length=100)),
                ('field_label', models.CharField(help_text='Display label: Party A Name', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('currency', 'Currency (₹)'), ('pan_number', 'PAN Number'), ('gst_number', 'GST Number'), ('dropdown', 'Dropdown Selection'), ('checkbox', 'Checkbox')], default='text', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('validation_rules', models.JSONField(default=dict, help_text='{"min_length": 5, "max_length": 100, "regex": "pattern"}')),
                ('dropdown_options', models.JSONField(default=list, help_text='["Option 1", "Option 2", "Option 3"]')),
                ('placeholder_text', models.CharField(default='_____________', help_text='Text shown in document before filling', max_length=255)),
                ('help_text', models.TextField(blank=True, help_text='Help text shown to user')),
                ('position_index', models.IntegerField(default=0, help_text='Order in form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visual_placeholders',
                'ordering': ['template', 'position_index'],
            },
        ),
        migrations.CreateModel(
            name='PlaceholderRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_index', models.IntegerField(help_text='Which paragraph (0-indexed)')),
                ('run_index', models.IntegerField(default=0, help_text='Which run in paragraph')),
                ('char_start', models.IntegerField(help_text='Character start position in run')),
                ('char_end', models.IntegerField(help_text='Character end position in run')),
                ('page_number', models.IntegerField(default=1)),
                ('x_percent', models.FloatField(help_text='X position as % of page width')),
                ('y_percent', models.FloatField(help_text='Y position as % of page height')),
                ('width_percent', models.FloatField(help_text='Width as % of page width')),
                ('height_percent', models.FloatField(help_text='Height as % of page height')),
                ('selected_text', models.CharField(help_text='Original text that was selected', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='templates.visualplaceholder')),
            ],
            options={
                'db_table': 'placeholder_regions',
                'ordering': ['placeholder', 'paragraph_index', 'char_start'],
            },
        ),
        migrations.CreateModel(
            name='VisualTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('original_file', models.FileField(upload_to='visual_templates/%Y/%m/')),
                ('html_preview', models.TextField(blank=True)),
                ('document_structure', models.JSONField(default=dict, help_text='Paragraph/run structure from python-docx')),
                ('file_size', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=1)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft - Being Built'), ('active', 'Active - Ready for Use'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_templates_created', to=settings.AUTH_USER_MODEL)),
                ('legacy_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_version', to='templates.template')),
            ],
            options={
                'db_table': 'visual_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='visualplaceholder',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='templates.visualtemplate'),
        ),
        migrations.CreateModel(
            name='VisualAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_values', models.JSONField(default=dict, help_text='{"party_a_name": "ABC Company", "date": "2026-02-03"}')),
                ('generated_file', models.FileField(blank=True, help_text='Final DOCX with filled data', null=True, upload_to='visual_agreements/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF export', null=True, upload_to='visual_agreements_pdf/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('signed', 'Signed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='templates.visualtemplate')),
            ],
            options={
                'db_table': 'visual_agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='visualplaceholder',
            unique_together={('template', 'field_name')},
        ),
    ]
